#!/bin/bash
./lang test7/$1.lang langout
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
  echo $1 Compilation FAILED ---------
  exit
fi

slasm langout.sl io320.sl
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
  echo $1 Assembly FAILED ---------
  exit
fi

stackl langout.slb > out

diff -qbwB out test7/$1.correct
RETVAL=$?
[ $RETVAL -eq 0 ] && echo $1 PASSED
[ $RETVAL -ne 0 ] && echo $1 FAILED -----
exit $RETVAL

